### ISSUE TITLE
End Date must be greater than Start Date

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/date#17]
I enter this:

![end-date](https://cloud.githubusercontent.com/assets/13283396/14035159/36f012c8-f1e8-11e5-8a31-bcd067f5b54b.PNG)

and get this error:

![end date error](https://cloud.githubusercontent.com/assets/13283396/14035171/55d0d2f4-f1e8-11e5-912f-73fc02ba45b3.PNG)

**Comment by signalpoint** [comment]
@mkinnan Thank you for your pull request here! I had to manually merge your fix (and then simplified it) because you had modified the date.js file directly, instead of editing a file(s) in the `src` directory of the date module, and then running `grunt` to compile the `src` files into the `date.js` and `date.min.js` files. No big deal, this was a very recent change on my part, but now it follow along with DG core in that all the source code lives in the `src` directory, and then is compiled into 2 final .js files.

**Comment by mkinnan** [comment]
It is fixed on Ripple Emulator or Android, but for some reason I still get this error on iOS devices.
