### ISSUE TITLE
Editing node with date field isn't showing correct date/time

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/date#18]
Notice the **HOUR** and **AM/PM** gets changed below. The **HOUR** gets changed exactly by 6 hours, which is the difference between UTC and the timezone of the user. Not sure how easy this is to fix, but going all UTC as website/user default will probably get around this.

**I enter this into the node when created new:**

![new-node](https://cloud.githubusercontent.com/assets/13283396/14035647/cb25f98a-f1ed-11e5-80af-ba435004c0d3.PNG)

**Here is what it shows when I edit the node:**

![edit-node](https://cloud.githubusercontent.com/assets/13283396/14035649/cf35a9c6-f1ed-11e5-8d0d-ec671e71cfee.PNG)

**Comment by mkinnan** [comment]
Changing to default UTC gets around the hour ussue, but the am/pm still defaults back to am when pm was saved.

**Comment by signalpoint** [comment]
@mkinnan With the latest commit, the am/pm widget now pays attention to existing values. Thank you for pointing me in the right direction on this!

**Comment by signalpoint** [comment]
@mkinnan Thank you for your pull request here! I had to manually merge your fix (and then simplified it) because you had modified the date.js file directly, instead of editing a file(s) in the `src` directory of the date module, and then running `grunt` to compile the `src` files into the `date.js` and `date.min.js` files. No big deal, this was a very recent change on my part, but now it follow along with DG core in that all the source code lives in the `src` directory, and then is compiled into 2 final .js files.

**Comment by signalpoint** [comment]
FYI, #22 was related to @mkinnan's issues here.

**Comment by mkinnan** [comment]
It is fixed on Ripple Emulator or Android, but for some reason I still get this error on iOS devices.
